language: node_js
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- gem install sass

node_js:
- '0.11'
- '0.12'

before_script:
- 'npm -g install bower bower-installer gulp'
- 'npm install'
- 'bower install'
- 'bower-installer'

script: gulp